/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCasino;
import ec.edu.ups.controlador.ControladorJugador;
import ec.edu.ups.hilo.H2M1;
import ec.edu.ups.hilo.H3M1;
import ec.edu.ups.hilo.H4M1;
import ec.edu.ups.hilo.HM1;
import ec.edu.ups.hilo.hiloJugador1;
import ec.edu.ups.hilo.hiloJugador2;
import ec.edu.ups.hilo.hiloJugador3;
import ec.edu.ups.hilo.hiloJugador4;
import ec.edu.ups.hilo.hilos;
import ec.edu.ups.modelo.Casino;
import ec.edu.ups.modelo.Jugador;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class RuletaFrancesa extends javax.swing.JFrame {

    private VentanaDeOpciones ventanaDeOpciones;
    private List<JButton> numeros;
    private hilos h;
    private hiloJugador1 h1;
    private hiloJugador2 h2;
    private hiloJugador3 h3;
    private hiloJugador4 h4;
    private HM1 hM1;
    private H2M1 hM2;
    private H3M1 hM3;
    private H4M1 hM4;
    private final Random randomico = new Random();
    private String nGanador, dine, dine2, dine3, dine4, dine5, nom1, nom2, nom3, nom4,i,p;
    private int nu, nu2, nu3;
    private Casino casino;
    private Jugador jugador;
    private ControladorCasino controladorCasino;
    private ControladorJugador controladorJugador;
    int contV1 = 0;
    int contV1T=0;
    int contV2 = 0;
    int contV3 = 0;
    int contVT = 0;
    int contD1 = 0;
    int contD2 = 0;
    int contD3 = 0;
    int contDT = 0;
    int apuestas = 0;
    double perdidoaumentado=0;

    /**
     * Creates new form RuletaFrancesa
     */
    public RuletaFrancesa() {
        initComponents();
        controladorCasino = new ControladorCasino();
        controladorJugador = new ControladorJugador();
        casino = new Casino();
        jugador = new Jugador();
        numeros = new ArrayList<JButton>();
        ventanaDeOpciones = new VentanaDeOpciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton32 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j22 = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j12 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j16 = new javax.swing.JButton();
        j10 = new javax.swing.JButton();
        j13 = new javax.swing.JButton();
        j19 = new javax.swing.JButton();
        j34 = new javax.swing.JButton();
        j31 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j25 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j15 = new javax.swing.JButton();
        j11 = new javax.swing.JButton();
        j28 = new javax.swing.JButton();
        j14 = new javax.swing.JButton();
        j17 = new javax.swing.JButton();
        j20 = new javax.swing.JButton();
        j23 = new javax.swing.JButton();
        j26 = new javax.swing.JButton();
        j29 = new javax.swing.JButton();
        j32 = new javax.swing.JButton();
        j35 = new javax.swing.JButton();
        j18 = new javax.swing.JButton();
        j21 = new javax.swing.JButton();
        j24 = new javax.swing.JButton();
        j27 = new javax.swing.JButton();
        j30 = new javax.swing.JButton();
        j33 = new javax.swing.JButton();
        j36 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNombre1 = new javax.swing.JTextField();
        jNombre2 = new javax.swing.JTextField();
        jNombre3 = new javax.swing.JTextField();
        jNombre4 = new javax.swing.JTextField();
        jDinero1 = new javax.swing.JTextField();
        jDinero2 = new javax.swing.JTextField();
        jDinero3 = new javax.swing.JTextField();
        jDinero4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDineroCasino = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        PI = new javax.swing.JToggleButton();
        NC = new javax.swing.JToggleButton();
        MG = new javax.swing.JToggleButton();
        ju2 = new javax.swing.JTextField();
        ju3 = new javax.swing.JTextField();
        ju4 = new javax.swing.JTextField();
        ju1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jButton32.setText("jButton32");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casino");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        j1.setBackground(new java.awt.Color(255, 0, 0));
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("3");

        j2.setBackground(new java.awt.Color(0, 0, 0));
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setText("2");

        j3.setBackground(new java.awt.Color(255, 0, 0));
        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.setText("1");

        j22.setBackground(new java.awt.Color(0, 0, 0));
        j22.setForeground(new java.awt.Color(255, 255, 255));
        j22.setText("22");

        j0.setBackground(new java.awt.Color(0, 153, 0));
        j0.setForeground(new java.awt.Color(255, 255, 255));
        j0.setText("0");

        j6.setBackground(new java.awt.Color(0, 0, 0));
        j6.setForeground(new java.awt.Color(255, 255, 255));
        j6.setText("6");

        j4.setBackground(new java.awt.Color(0, 0, 0));
        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.setText("4");

        j12.setBackground(new java.awt.Color(255, 0, 0));
        j12.setForeground(new java.awt.Color(255, 255, 255));
        j12.setText("12");

        j9.setBackground(new java.awt.Color(255, 0, 0));
        j9.setForeground(new java.awt.Color(255, 255, 255));
        j9.setText("9");

        j16.setBackground(new java.awt.Color(255, 0, 0));
        j16.setForeground(new java.awt.Color(255, 255, 255));
        j16.setText("16");

        j10.setBackground(new java.awt.Color(0, 0, 0));
        j10.setForeground(new java.awt.Color(255, 255, 255));
        j10.setText("10");

        j13.setBackground(new java.awt.Color(0, 0, 0));
        j13.setForeground(new java.awt.Color(255, 255, 255));
        j13.setText("13");

        j19.setBackground(new java.awt.Color(255, 0, 0));
        j19.setForeground(new java.awt.Color(255, 255, 255));
        j19.setText("19");

        j34.setBackground(new java.awt.Color(255, 0, 0));
        j34.setForeground(new java.awt.Color(255, 255, 255));
        j34.setText("34");

        j31.setBackground(new java.awt.Color(0, 0, 0));
        j31.setForeground(new java.awt.Color(255, 255, 255));
        j31.setText("31");

        j7.setBackground(new java.awt.Color(255, 0, 0));
        j7.setForeground(new java.awt.Color(255, 255, 255));
        j7.setText("7");

        j25.setBackground(new java.awt.Color(255, 0, 0));
        j25.setForeground(new java.awt.Color(255, 255, 255));
        j25.setText("25");

        j5.setBackground(new java.awt.Color(255, 0, 0));
        j5.setForeground(new java.awt.Color(255, 255, 255));
        j5.setText("5");

        j8.setBackground(new java.awt.Color(0, 0, 0));
        j8.setForeground(new java.awt.Color(255, 255, 255));
        j8.setText("8");

        j15.setBackground(new java.awt.Color(0, 0, 0));
        j15.setForeground(new java.awt.Color(255, 255, 255));
        j15.setText("15");

        j11.setBackground(new java.awt.Color(0, 0, 0));
        j11.setForeground(new java.awt.Color(255, 255, 255));
        j11.setText("11");

        j28.setBackground(new java.awt.Color(0, 0, 0));
        j28.setForeground(new java.awt.Color(255, 255, 255));
        j28.setText("28");

        j14.setBackground(new java.awt.Color(255, 0, 0));
        j14.setForeground(new java.awt.Color(255, 255, 255));
        j14.setText("14");

        j17.setBackground(new java.awt.Color(0, 0, 0));
        j17.setForeground(new java.awt.Color(255, 255, 255));
        j17.setText("17");

        j20.setBackground(new java.awt.Color(0, 0, 0));
        j20.setForeground(new java.awt.Color(255, 255, 255));
        j20.setText("20");

        j23.setBackground(new java.awt.Color(255, 0, 0));
        j23.setForeground(new java.awt.Color(255, 255, 255));
        j23.setText("23");

        j26.setBackground(new java.awt.Color(0, 0, 0));
        j26.setForeground(new java.awt.Color(255, 255, 255));
        j26.setText("26");

        j29.setBackground(new java.awt.Color(0, 0, 0));
        j29.setForeground(new java.awt.Color(255, 255, 255));
        j29.setText("29");

        j32.setBackground(new java.awt.Color(255, 0, 0));
        j32.setForeground(new java.awt.Color(255, 255, 255));
        j32.setText("32");

        j35.setBackground(new java.awt.Color(0, 0, 0));
        j35.setForeground(new java.awt.Color(255, 255, 255));
        j35.setText("35");

        j18.setBackground(new java.awt.Color(255, 0, 0));
        j18.setForeground(new java.awt.Color(255, 255, 255));
        j18.setText("18");

        j21.setBackground(new java.awt.Color(255, 0, 0));
        j21.setForeground(new java.awt.Color(255, 255, 255));
        j21.setText("21");

        j24.setBackground(new java.awt.Color(0, 0, 0));
        j24.setForeground(new java.awt.Color(255, 255, 255));
        j24.setText("24");

        j27.setBackground(new java.awt.Color(255, 0, 0));
        j27.setForeground(new java.awt.Color(255, 255, 255));
        j27.setText("27");

        j30.setBackground(new java.awt.Color(255, 0, 0));
        j30.setForeground(new java.awt.Color(255, 255, 255));
        j30.setText("30");

        j33.setBackground(new java.awt.Color(0, 0, 0));
        j33.setForeground(new java.awt.Color(255, 255, 255));
        j33.setText("33");

        j36.setBackground(new java.awt.Color(255, 0, 0));
        j36.setForeground(new java.awt.Color(255, 255, 255));
        j36.setText("36");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/como-jugar-ruleta-online-consejos-reglas-tipo-L-xmnw1P.gif"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/jugador.png"))); // NOI18N
        jLabel2.setText("Jugador 1:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/jugador.png"))); // NOI18N
        jLabel3.setText("Jugador 2:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/jugador.png"))); // NOI18N
        jLabel4.setText("Jugador 3:");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/jugador.png"))); // NOI18N
        jLabel5.setText("Jugador 4:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/iconos-de-dinero.png"))); // NOI18N
        jLabel6.setText("Dinero:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/iconos-de-dinero.png"))); // NOI18N
        jLabel7.setText("Dinero:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/iconos-de-dinero.png"))); // NOI18N
        jLabel8.setText("Dinero:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/iconos-de-dinero.png"))); // NOI18N
        jLabel9.setText("Dinero:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/iconos-de-dinero.png"))); // NOI18N
        jLabel10.setText("Dinero del Casino");

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/opciones.png"))); // NOI18N
        jButton39.setText("Opciones");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/ficha-de-poker.png"))); // NOI18N
        jButton40.setText("Jugar");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/ruleta.png"))); // NOI18N
        PI.setText("Par/Impar");
        PI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PIMouseClicked(evt);
            }
        });

        NC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/ruleta.png"))); // NOI18N
        NC.setText("Numero Concreto");
        NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCActionPerformed(evt);
            }
        });

        MG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/ruleta.png"))); // NOI18N
        MG.setText("MartinGala");
        MG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MGActionPerformed(evt);
            }
        });

        jLabel11.setText("J1:");

        jLabel12.setText("J2:");

        jLabel13.setText("J3:");

        jLabel14.setText("J4:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDinero4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jDinero2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(4, 4, 4)
                                                    .addComponent(jDinero3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jDinero1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(j0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(j8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(j12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j11))))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(j15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(j14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j17))
                                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(j33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(j31))
                                    .addComponent(j32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j34))))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDineroCasino))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton39)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NC, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PI))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ju1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ju2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ju3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ju4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MG)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton39)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NC)
                                    .addComponent(PI)
                                    .addComponent(MG))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ju2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ju3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ju4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ju1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDinero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDinero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDinero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jDinero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jButton40)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDineroCasino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(j5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(j0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(j18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(j20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(j31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        ventanaDeOpciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        numeros.add(j0);
        numeros.add(j1);
        numeros.add(j2);
        numeros.add(j3);
        numeros.add(j4);
        numeros.add(j5);
        numeros.add(j6);
        numeros.add(j7);
        numeros.add(j8);
        numeros.add(j9);
        numeros.add(j10);
        numeros.add(j11);
        numeros.add(j12);
        numeros.add(j13);
        numeros.add(j14);
        numeros.add(j15);
        numeros.add(j16);
        numeros.add(j17);
        numeros.add(j18);
        numeros.add(j19);
        numeros.add(j20);
        numeros.add(j21);
        numeros.add(j22);
        numeros.add(j23);
        numeros.add(j24);
        numeros.add(j25);
        numeros.add(j26);
        numeros.add(j27);
        numeros.add(j28);
        numeros.add(j29);
        numeros.add(j30);
        numeros.add(j31);
        numeros.add(j32);
        numeros.add(j33);
        numeros.add(j34);
        numeros.add(j35);
        numeros.add(j36);
        
        if (!ju1.getText().equals("") || !ju2.getText().equals("") || !ju3.getText().equals("") || !ju4.getText().equals("")) {
            for (int i = 0; i < 36; i++) {
                h = new hilos(numeros.get(i), 0, 0, 0);
            }
            randomico.nextInt(36);
            nGanador = String.valueOf(randomico.nextInt(36));
            if (NC.isSelected()) {
                System.out.println("1");
                try {
                    suma();
                } catch (Exception ex) {
                    Logger.getLogger(RuletaFrancesa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
if (PI.isSelected()) {
    System.out.println("2");
                try {
                    suma2();
                } catch (Exception ex) {
                    Logger.getLogger(RuletaFrancesa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
if (MG.isSelected()) {
    System.out.println("3");
                try {
                    suma3();
                } catch (Exception ex) {
                    Logger.getLogger(RuletaFrancesa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "faltan numeros");
        }


    }//GEN-LAST:event_jButton40ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Casino casino1 = controladorCasino.buscar(201L);
        dine = String.valueOf(casino1.getDinero());
        jDineroCasino.setText(dine);
        //Jugador  
        Jugador jugador1 = controladorJugador.buscar(301L);
        Jugador jugador5 = controladorJugador.buscar(301L);
        dine2 = String.valueOf(jugador1.getDinero());
        nom1 = jugador5.getNickname();
        jNombre1.setText(nom1);
        jDinero1.setText(dine2);
        Jugador jugador2 = controladorJugador.buscar(302L);
        Jugador jugador6 = controladorJugador.buscar(302L);
        dine3 = String.valueOf(jugador2.getDinero());
        jDinero2.setText(dine3);
        nom2 = jugador6.getNickname();
        jNombre2.setText(nom2);
        Jugador jugador3 = controladorJugador.buscar(303L);
        Jugador jugador7 = controladorJugador.buscar(303L);
        dine4 = String.valueOf(jugador3.getDinero());
        jDinero3.setText(dine4);
        nom3 = jugador7.getNickname();
        jNombre3.setText(nom3);
        Jugador jugador4 = controladorJugador.buscar(304L);
        Jugador jugador8 = controladorJugador.buscar(304L);
        dine5 = String.valueOf(jugador4.getDinero());
        jDinero4.setText(dine5);
        nom4 = jugador8.getNickname();
        jNombre4.setText(nom4);
//jugadores
 
    }//GEN-LAST:event_formWindowActivated

    private void PIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PIMouseClicked
     hM1 = new HM1(ju1);
     hM2 = new H2M1(ju2);
     hM3 = new H3M1(ju3);
     hM4 = new H4M1(ju4);
    }//GEN-LAST:event_PIMouseClicked

    private void NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCActionPerformed
        h1 = new hiloJugador1(ju1);
        h2 = new hiloJugador2(ju2);
        h3 = new hiloJugador3(ju3);
        h4 = new hiloJugador4(ju4);
    }//GEN-LAST:event_NCActionPerformed

    private void MGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MGActionPerformed
      h1 = new hiloJugador1(ju1);
        h2 = new hiloJugador2(ju2);
        h3 = new hiloJugador3(ju3);
        h4 = new hiloJugador4(ju4);

    }//GEN-LAST:event_MGActionPerformed
    public void suma() throws Exception {
        if (ju1.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero ganador es " + ju1.getText());
            double ganado = 360.00;
            double sumaj = Double.parseDouble(jDinero1.getText());
            double suma2j = ganado + sumaj;
            Jugador juga = controladorJugador.buscar(301L);
            juga.setDinero(suma2j);
            double ingresos = ganado + 360.00;
            juga.setDineroGanado(ingresos);
            Jugador juga1 = controladorJugador.buscar(301L);
            contV1 = juga1.getVictoriasM1() + 1;
            contV1T= juga1.getdTotales()+1;
            juga1.setVictoriasM1(contV1);
            juga1.setvTotales(contV1T);
            apuestas = juga1.getnApuestas() + 1;
            juga1.setnApuestas(apuestas);
            controladorJugador.actualizar(juga);
        } else{
        double perdido = 10.00;
            double restaj = Double.parseDouble(jDinero1.getText());
            double resta2j = -perdido + restaj;
            Jugador juga = controladorJugador.buscar(301L);
            juga.setDinero(resta2j);
            double egresos = perdido + 10.00;
            juga.setDineroPerdido(egresos);
            Jugador juga1 = controladorJugador.buscar(301L);
            contV1 = juga1.getDerrotasM1()+ 1;
            contV1T= juga1.getdTotales()+1;
            juga1.setDerrotasM1(contV1);
            juga1.setdTotales(contV1T);
            apuestas = juga1.getnApuestas() + 1;
            juga1.setnApuestas(apuestas);
            controladorJugador.actualizar(juga);
        }
        if (ju2.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju2.getText());
       double ganado = 360.00;
            double sumaj2 = Double.parseDouble(jDinero1.getText());
            double suma2j2 = ganado + sumaj2;
            Jugador juga2 = controladorJugador.buscar(302L);
            juga2.setDinero(suma2j2);
            double ingresos = ganado + 360.00;
            juga2.setDineroGanado(ingresos);
            Jugador juga12 = controladorJugador.buscar(302L);
            contV1 = juga12.getVictoriasM1() + 1;
            contV1T= juga12.getdTotales()+1;
            juga12.setVictoriasM1(contV1);
            juga12.setvTotales(contV1T);
            apuestas = juga12.getnApuestas() + 1;
            juga12.setnApuestas(apuestas);
            controladorJugador.actualizar(juga2);
        } else{
        double perdido = 10.00;
            double restaj2 = Double.parseDouble(jDinero1.getText());
            double resta2j2 = -perdido + restaj2;
            Jugador juga2 = controladorJugador.buscar(302L);
            juga2.setDinero(resta2j2);
            double egresos = perdido + 10.00;
            juga2.setDineroPerdido(egresos);
            Jugador juga12 = controladorJugador.buscar(302L);
            contV1 = juga12.getDerrotasM1()+ 1;
            contV1T= juga12.getdTotales()+1;
            juga12.setDerrotasM1(contV1);
            juga12.setdTotales(contV1T);
            apuestas = juga12.getnApuestas() + 1;
            juga12.setnApuestas(apuestas);
            controladorJugador.actualizar(juga2);
        }
        if (ju3.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju3.getText());
       double ganado = 360.00;
            double sumaj3 = Double.parseDouble(jDinero1.getText());
            double suma3j = ganado + sumaj3;
            Jugador juga3 = controladorJugador.buscar(303L);
            juga3.setDinero(suma3j);
            double ingresos = ganado + 360.00;
            juga3.setDineroGanado(ingresos);
            Jugador juga13 = controladorJugador.buscar(303L);
            contV1 = juga13.getVictoriasM1() + 1;
            contV1T= juga13.getdTotales()+1;
            juga13.setVictoriasM1(contV1);
            juga13.setvTotales(contV1T);
            apuestas = juga13.getnApuestas() + 1;
            juga13.setnApuestas(apuestas);
            controladorJugador.actualizar(juga3);
        } else{
        double perdido = 10.00;
            double restaj3 = Double.parseDouble(jDinero1.getText());
            double resta2j3 = -perdido + restaj3;
            Jugador juga3 = controladorJugador.buscar(303L);
            juga3.setDinero(resta2j3);
            double egresos = perdido + 10.00;
            juga3.setDineroPerdido(egresos);
            Jugador juga13 = controladorJugador.buscar(303L);
            contV1 = juga13.getDerrotasM1()+ 1;
            contV1T= juga13.getdTotales()+1;
            juga13.setDerrotasM1(contV1);
            juga13.setdTotales(contV1T);
            apuestas = juga13.getnApuestas() + 1;
            juga13.setnApuestas(apuestas);
            controladorJugador.actualizar(juga3);
        }
        if (ju4.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju1.getText());
       double ganado = 360.00;
            double sumaj4 = Double.parseDouble(jDinero1.getText());
            double suma4j = ganado + sumaj4;
            Jugador juga4 = controladorJugador.buscar(304L);
            juga4.setDinero(suma4j);
            double ingresos = ganado + 360.00;
            juga4.setDineroGanado(ingresos);
            Jugador juga14 = controladorJugador.buscar(304L);
            contV1 = juga14.getVictoriasM1() + 1;
            contV1T= juga14.getdTotales()+1;
            juga14.setVictoriasM1(contV1);
            juga14.setvTotales(contV1T);
            apuestas = juga14.getnApuestas() + 1;
            juga14.setnApuestas(apuestas);
            controladorJugador.actualizar(juga4);
        }else{
        double perdido = 10.00;
            double restaj4 = Double.parseDouble(jDinero1.getText());
            double resta2j4 = -perdido + restaj4;
            Jugador juga4 = controladorJugador.buscar(304L);
            juga4.setDinero(resta2j4);
            double egresos = perdido + 10.00;
            juga4.setDineroPerdido(egresos);
            Jugador juga14 = controladorJugador.buscar(304L);
            contV1 = juga14.getDerrotasM1()+ 1;
            contV1T= juga14.getdTotales()+1;
            juga14.setDerrotasM1(contV1);
            juga14.setdTotales(contV1T);
            apuestas = juga14.getnApuestas() + 1;
            juga14.setnApuestas(apuestas);
            controladorJugador.actualizar(juga4);
        } 
        if(!ju4.getText().equals(nGanador)||!ju3.getText().equals(nGanador)||!ju2.getText().equals(nGanador)||!ju1.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "gana el casino");
            double ganado = 360.00;
            double suma = Double.parseDouble(jDineroCasino.getText());
            double suma2 = ganado + suma;
            Casino casi = controladorCasino.buscar(201L);
            casi.setDinero(suma2);
            double ingresos = ganado + 360.00;
            casi.setDineroGanado(ingresos);
            controladorCasino.actualizar(casi);
            Casino casi1 = controladorCasino.buscar(201L);
            contV1 = casi1.getVictoriasM1() + 1;
            contV1T= casi1.getdTotales()+1;
            casi1.setVictoriasM1(contV1);
            casi1.setvTotales(contV1T);
            apuestas = casi1.getnApuestas() + 1;
            casi1.setnApuestas(apuestas);
            controladorCasino.actualizar(casi);
        }else{
            double restado = 10.00;
            double resta = Double.parseDouble(jDineroCasino.getText());
            double resta2 = -restado + resta;
            Casino casi = controladorCasino.buscar(201L);
            casi.setDinero(resta2);
            double egresos = restado + 10.00;
            casi.setDineroPerdido(egresos);
            controladorCasino.actualizar(casi);
            Casino casi1 = controladorCasino.buscar(201L);
            contV1 = casi1.getDerrotasM1()+ 1;
            contV1T= casi1.getdTotales()+1;
            casi1.setDerrotasM1(contV1);
            casi1.setdTotales(contV1T);
            apuestas = casi1.getnApuestas() + 1;
            casi1.setnApuestas(apuestas);
            controladorCasino.actualizar(casi);
        }
    }
    public void suma2() throws Exception{
 if(randomico.nextInt(37)%2==0){
  p= ju1.getText();
 }else {
      i = ju1.getText();
 }
        
    if (ju1.getText().equals(p)||ju1.getText().equals(i)) {
            JOptionPane.showMessageDialog(this, "El numero ganador es " + ju1.getText());
            double ganado = 20.00;
            double sumaj = Double.parseDouble(jDinero1.getText());
            double suma2j = ganado + sumaj;
            Jugador juga = controladorJugador.buscar(301L);
            juga.setDinero(suma2j);
            double ingresos = ganado + 20.00;
            juga.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga);
            Jugador juga1 = controladorJugador.buscar(301L);
            contV1 = juga1.getVictoriasM2() + 1;
            contV1T= juga1.getdTotales()+1;
            juga1.setVictoriasM2(contV1);
            juga1.setvTotales(contV1T);
            apuestas = juga1.getnApuestas() + 1;
            juga1.setnApuestas(apuestas);
            controladorJugador.actualizar(juga);
        } else{
        double perdido = 10.00;
            double restaj = Double.parseDouble(jDinero1.getText());
            double resta2j = -perdido + restaj;
            Jugador juga = controladorJugador.buscar(301L);
            juga.setDinero(resta2j);
            double egresos = perdido + 10.00;
            juga.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga);
            Jugador juga1 = controladorJugador.buscar(301L);
            contV1 = juga1.getDerrotasM2()+ 1;
            contV1T= juga1.getdTotales()+1;
            juga1.setDerrotasM2(contV1);
            juga1.setdTotales(contV1T);
            apuestas = juga1.getnApuestas() + 1;
            juga1.setnApuestas(apuestas);
            controladorJugador.actualizar(juga);
        }
        if (ju2.getText().equals(p)||ju2.getText().equals(i)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju2.getText());
       double ganado = 20.00;
            double sumaj2 = Double.parseDouble(jDinero1.getText());
            double suma2j2 = ganado + sumaj2;
            Jugador juga2 = controladorJugador.buscar(302L);
            juga2.setDinero(suma2j2);
            double ingresos = ganado + 20.00;
            juga2.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga2);
            Jugador juga12 = controladorJugador.buscar(302L);
            contV1 = juga12.getVictoriasM2() + 1;
            contV1T= juga12.getdTotales()+1;
            juga12.setVictoriasM2(contV1);
            juga12.setvTotales(contV1T);
            apuestas = juga12.getnApuestas() + 1;
            juga12.setnApuestas(apuestas);
            controladorJugador.actualizar(juga2);
        } else{
        double perdido = 10.00;
            double restaj2 = Double.parseDouble(jDinero1.getText());
            double resta2j2 = -perdido + restaj2;
            Jugador juga2 = controladorJugador.buscar(302L);
            juga2.setDinero(resta2j2);
            double egresos = perdido + 10.00;
            juga2.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga2);
            Jugador juga12 = controladorJugador.buscar(302L);
            contV1 = juga12.getDerrotasM2()+ 1;
            contV1T= juga12.getdTotales()+1;
            juga12.setDerrotasM2(contV1);
            juga12.setdTotales(contV1T);
            apuestas = juga12.getnApuestas() + 1;
            juga12.setnApuestas(apuestas);
            controladorJugador.actualizar(juga2);
        }
        if (ju3.getText().equals(p)||ju3.getText().equals(i)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju3.getText());
       double ganado = 20.00;
            double sumaj3 = Double.parseDouble(jDinero1.getText());
            double suma3j = ganado + sumaj3;
            Jugador juga3 = controladorJugador.buscar(303L);
            juga3.setDinero(suma3j);
            double ingresos = ganado + 20.00;
            juga3.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga3);
            Jugador juga13 = controladorJugador.buscar(303L);
            contV1 = juga13.getVictoriasM2() + 1;
            contV1T= juga13.getdTotales()+1;
            juga13.setVictoriasM2(contV1);
            juga13.setvTotales(contV1T);
            apuestas = juga13.getnApuestas() + 1;
            juga13.setnApuestas(apuestas);
            controladorJugador.actualizar(juga3);
        } else{
        double perdido = 10.00;
            double restaj3 = Double.parseDouble(jDinero1.getText());
            double resta2j3 = -perdido + restaj3;
            Jugador juga3 = controladorJugador.buscar(303L);
            juga3.setDinero(resta2j3);
            double egresos = perdido + 10.00;
            juga3.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga3);
            Jugador juga13 = controladorJugador.buscar(303L);
            contV1 = juga13.getDerrotasM2()+ 1;
            contV1T= juga13.getdTotales()+1;
            juga13.setDerrotasM2(contV1);
            juga13.setdTotales(contV1T);
            apuestas = juga13.getnApuestas() + 1;
            juga13.setnApuestas(apuestas);
            controladorJugador.actualizar(juga3);
        }
        if (ju4.getText().equals(p)||ju4.getText().equals(i)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju4.getText());
       double ganado = 20.00;
            double sumaj4 = Double.parseDouble(jDinero1.getText());
            double suma4j = ganado + sumaj4;
            Jugador juga4 = controladorJugador.buscar(304L);
            juga4.setDinero(suma4j);
            double ingresos = ganado + 20.00;
            juga4.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga4);
            Jugador juga14 = controladorJugador.buscar(304L);
            contV1 = juga14.getVictoriasM2() + 1;
            contV1T= juga14.getdTotales()+1;
            juga14.setVictoriasM2(contV1);
            juga14.setvTotales(contV1T);
            apuestas = juga14.getnApuestas() + 1;
            juga14.setnApuestas(apuestas);
            controladorJugador.actualizar(juga4);
        }else{
        double perdido = 10.00;
            double restaj4 = Double.parseDouble(jDinero1.getText());
            double resta2j4 = -perdido +restaj4;
            Jugador juga4 = controladorJugador.buscar(304L);
            juga4.setDinero(resta2j4);
            double egresos = perdido + 10.00;
            juga4.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga4);
            Jugador juga14 = controladorJugador.buscar(304L);
            contV1 = juga14.getDerrotasM2()+ 1;
            contV1T= juga14.getdTotales()+1;
            juga14.setDerrotasM2(contV1);
            juga14.setdTotales(contV1T);
            apuestas = juga14.getnApuestas() + 1;
            juga14.setnApuestas(apuestas);
            controladorJugador.actualizar(juga4);
        } 
        if(!ju4.getText().equals(nGanador)||!ju3.getText().equals(nGanador)||!ju2.getText().equals(nGanador)||!ju1.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "gana el casino");
            double ganado = 20.00;
            double suma = Double.parseDouble(jDineroCasino.getText());
            double suma2 = ganado + suma;
            Casino casi = controladorCasino.buscar(201L);
            casi.setDinero(suma2);
            double ingresos = ganado + 20.00;
            casi.setDineroGanado(ingresos);
            controladorCasino.actualizar(casi);
            Casino casi1 = controladorCasino.buscar(201L);
            contV1 = casi1.getVictoriasM2() + 1;
            contV1T= casi1.getdTotales()+1;
            casi1.setVictoriasM2(contV1);
            casi1.setvTotales(contV1T);
            apuestas = casi1.getnApuestas() + 1;
            casi1.setnApuestas(apuestas);
            controladorCasino.actualizar(casi);
        }else{
            double restado = 10.00;
            double resta = Double.parseDouble(jDineroCasino.getText());
            double resta2 = -restado + resta;
            Casino casi = controladorCasino.buscar(201L);
            casi.setDinero(resta2);
            double egresos = restado + 10.00;
            casi.setDineroPerdido(egresos);
            controladorCasino.actualizar(casi);
            Casino casi1 = controladorCasino.buscar(201L);
            contV1 = casi1.getDerrotasM2()+ 1;
            contV1T= casi1.getdTotales()+1;
            casi1.setDerrotasM2(contV1);
            casi1.setdTotales(contV1T);
            apuestas = casi1.getnApuestas() + 1;
            casi1.setnApuestas(apuestas);
            controladorCasino.actualizar(casi);
        }
    }
    public void suma3() throws Exception {
        if (ju1.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero ganador es " + ju1.getText());
            double ganado = 360.00;
            double sumaj = Double.parseDouble(jDinero1.getText());
            double suma2j = ganado + sumaj;
            Jugador juga = controladorJugador.buscar(301L);
            juga.setDinero(suma2j);
            double ingresos = ganado + 360.00;
            juga.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga);
            Jugador juga1 = controladorJugador.buscar(301L);
            contV1 = juga1.getVictoriasM3() + 1;
            contV1T= juga1.getdTotales()+1;
            juga1.setVictoriasM3(contV1);
            juga1.setvTotales(contV1T);
            apuestas = juga1.getnApuestas() + 1;
            juga1.setnApuestas(apuestas);
            controladorJugador.actualizar(juga);
        } else{
        double perdidoaumentado1 = perdidoaumentado+10.00;
            double restaj = Double.parseDouble(jDinero1.getText());
            double resta2j = -perdidoaumentado1 + restaj;
            Jugador juga = controladorJugador.buscar(301L);
            juga.setDinero(resta2j);
            double egresos = perdidoaumentado1 + 10.00;
            juga.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga);
            Jugador juga1 = controladorJugador.buscar(301L);
            contV1 = juga1.getDerrotasM3()+ 1;
            contV1T= juga1.getdTotales()+1;
            juga1.setDerrotasM3(contV1);
            juga1.setdTotales(contV1T);
            apuestas = juga1.getnApuestas() + 1;
            juga1.setnApuestas(apuestas);
            controladorJugador.actualizar(juga);
        }
        if (ju2.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju2.getText());
       double ganado = 360.00;
            double sumaj2 = Double.parseDouble(jDinero1.getText());
            double suma2j2 = ganado + sumaj2;
            Jugador juga2 = controladorJugador.buscar(302L);
            juga2.setDinero(suma2j2);
            double ingresos = ganado + 360.00;
            juga2.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga2);
            Jugador juga12 = controladorJugador.buscar(302L);
            contV1 = juga12.getVictoriasM3() + 1;
            contV1T= juga12.getdTotales()+1;
            juga12.setVictoriasM3(contV1);
            juga12.setvTotales(contV1T);
            apuestas = juga12.getnApuestas() + 1;
            juga12.setnApuestas(apuestas);
            controladorJugador.actualizar(juga2);
        } else{
        double perdidoaumentado1 = perdidoaumentado+10.00;
            double restaj2 = Double.parseDouble(jDinero1.getText());
            double resta2j2 = -perdidoaumentado1 + restaj2;
            Jugador juga2 = controladorJugador.buscar(302L);
            juga2.setDinero(resta2j2);
            double egresos = perdidoaumentado1 + 10.00;
            juga2.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga2);
            Jugador juga12 = controladorJugador.buscar(302L);
            contV1 = juga12.getDerrotasM3()+ 1;
            contV1T= juga12.getdTotales()+1;
            juga12.setDerrotasM3(contV1);
            juga12.setdTotales(contV1T);
            apuestas = juga12.getnApuestas() + 1;
            juga12.setnApuestas(apuestas);
            controladorJugador.actualizar(juga2);
        }
        if (ju3.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju3.getText());
       double ganado = 360.00;
            double sumaj3 = Double.parseDouble(jDinero1.getText());
            double suma3j = ganado + sumaj3;
            Jugador juga3 = controladorJugador.buscar(303L);
            juga3.setDinero(suma3j);
            double ingresos = ganado + 360.00;
            juga3.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga3);
            Jugador juga13 = controladorJugador.buscar(303L);
            contV1 = juga13.getVictoriasM3() + 1;
            contV1T= juga13.getdTotales()+1;
            juga13.setVictoriasM3(contV1);
            juga13.setvTotales(contV1T);
            apuestas = juga13.getnApuestas() + 1;
            juga13.setnApuestas(apuestas);
            controladorJugador.actualizar(juga3);
        } else{
        double perdidoaumentado1 = perdidoaumentado+10.00;
            double restaj3 = Double.parseDouble(jDinero1.getText());
            double resta2j3 = -perdidoaumentado1 + restaj3;
            Jugador juga3 = controladorJugador.buscar(303L);
            juga3.setDinero(resta2j3);
            double egresos = perdidoaumentado1 + 10.00;
            juga3.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga3);
            Jugador juga13 = controladorJugador.buscar(303L);
            contV1 = juga13.getDerrotasM3()+ 1;
            contV1T= juga13.getdTotales()+1;
            juga13.setDerrotasM3(contV1);
            juga13.setdTotales(contV1T);
            apuestas = juga13.getnApuestas() + 1;
            juga13.setnApuestas(apuestas);
            controladorJugador.actualizar(juga3);
        }
        if (ju4.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "El numero es " + ju4.getText());
       double ganado = 360.00;
            double sumaj4 = Double.parseDouble(jDinero1.getText());
            double suma4j = ganado + sumaj4;
            Jugador juga4 = controladorJugador.buscar(304L);
            juga4.setDinero(suma4j);
            double ingresos = ganado + 360.00;
            juga4.setDineroGanado(ingresos);
            controladorJugador.actualizar(juga4);
            Jugador juga14 = controladorJugador.buscar(304L);
            contV1 = juga14.getVictoriasM3() + 1;
            contV1T= juga14.getdTotales()+1;
            juga14.setVictoriasM3(contV1);
            juga14.setvTotales(contV1T);
            apuestas = juga14.getnApuestas() + 1;
            juga14.setnApuestas(apuestas);
            controladorJugador.actualizar(juga4);
        }else{
        double perdidoaumentado1 = perdidoaumentado+10.00;
            double restaj4 = Double.parseDouble(jDinero1.getText());
            double resta2j4 = -perdidoaumentado1 + restaj4;
            Jugador juga4 = controladorJugador.buscar(304L);
            juga4.setDinero(resta2j4);
            double egresos = perdidoaumentado1 + 10.00;
            juga4.setDineroPerdido(egresos);
            controladorJugador.actualizar(juga4);
            Jugador juga14 = controladorJugador.buscar(304L);
            contV1 = juga14.getDerrotasM3()+ 1;
            contV1T= juga14.getdTotales()+1;
            juga14.setDerrotasM3(contV1);
            juga14.setdTotales(contV1T);
            apuestas = juga14.getnApuestas() + 1;
            juga14.setnApuestas(apuestas);
            controladorJugador.actualizar(juga4);
        } 
        if(!ju4.getText().equals(nGanador)||!ju3.getText().equals(nGanador)||!ju2.getText().equals(nGanador)||!ju1.getText().equals(nGanador)) {
            JOptionPane.showMessageDialog(this, "gana el casino");
            double ganado = 360.00;
            double suma = Double.parseDouble(jDineroCasino.getText());
            double suma2 = ganado + suma;
            Casino casi = controladorCasino.buscar(201L);
            casi.setDinero(suma2);
            double ingresos = ganado + 360.00;
            casi.setDineroGanado(ingresos);
            controladorCasino.actualizar(casi);
            Casino casi1 = controladorCasino.buscar(201L);
            contV1 = casi1.getVictoriasM3() + 1;
            contV1T= casi1.getdTotales()+1;
            casi1.setVictoriasM3(contV1);
            casi1.setvTotales(contV1T);
            apuestas = casi1.getnApuestas() + 1;
            casi1.setnApuestas(apuestas);
            controladorCasino.actualizar(casi);
        }else{
            double restado = 10.00;
            double resta = Double.parseDouble(jDineroCasino.getText());
            double resta2 = -restado + resta;
            Casino casi = controladorCasino.buscar(201L);
            casi.setDinero(resta2);
            double egresos = restado + 10.00;
            casi.setDineroPerdido(egresos);
            controladorCasino.actualizar(casi);
            Casino casi1 = controladorCasino.buscar(201L);
            contV1 = casi1.getDerrotasM3()+ 1;
            contV1T= casi1.getdTotales()+1;
            casi1.setDerrotasM3(contV1);
            casi1.setdTotales(contV1T);
            apuestas = casi1.getnApuestas() + 1;
            casi1.setnApuestas(apuestas);
            controladorCasino.actualizar(casi);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RuletaFrancesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RuletaFrancesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RuletaFrancesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RuletaFrancesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RuletaFrancesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton MG;
    private javax.swing.JToggleButton NC;
    private javax.swing.JToggleButton PI;
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j10;
    private javax.swing.JButton j11;
    private javax.swing.JButton j12;
    private javax.swing.JButton j13;
    private javax.swing.JButton j14;
    private javax.swing.JButton j15;
    private javax.swing.JButton j16;
    private javax.swing.JButton j17;
    private javax.swing.JButton j18;
    private javax.swing.JButton j19;
    private javax.swing.JButton j2;
    private javax.swing.JButton j20;
    private javax.swing.JButton j21;
    private javax.swing.JButton j22;
    private javax.swing.JButton j23;
    private javax.swing.JButton j24;
    private javax.swing.JButton j25;
    private javax.swing.JButton j26;
    private javax.swing.JButton j27;
    private javax.swing.JButton j28;
    private javax.swing.JButton j29;
    private javax.swing.JButton j3;
    private javax.swing.JButton j30;
    private javax.swing.JButton j31;
    private javax.swing.JButton j32;
    private javax.swing.JButton j33;
    private javax.swing.JButton j34;
    private javax.swing.JButton j35;
    private javax.swing.JButton j36;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JTextField jDinero1;
    private javax.swing.JTextField jDinero2;
    private javax.swing.JTextField jDinero3;
    private javax.swing.JTextField jDinero4;
    private javax.swing.JTextField jDineroCasino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombre1;
    private javax.swing.JTextField jNombre2;
    private javax.swing.JTextField jNombre3;
    private javax.swing.JTextField jNombre4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ju1;
    private javax.swing.JTextField ju2;
    private javax.swing.JTextField ju3;
    private javax.swing.JTextField ju4;
    // End of variables declaration//GEN-END:variables
}
