/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCasino;
import ec.edu.ups.controlador.ControladorJugador;
import ec.edu.ups.modelo.Casino;
import ec.edu.ups.modelo.Jugador;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class VentanaDeOpciones extends javax.swing.JFrame {
//ventana
private RuletaFrancesa ruletaFrancesa;
//modelo
private Jugador jugador;
private Casino casino;
//controlador
private ControladorJugador controladorJugador;
private ControladorCasino controladorCasino;
//dato
private double dinero,dCasino;

    /**
     * Creates new form VentanaDeOpciones
     */
    public VentanaDeOpciones() {
        initComponents();
        //controlador
      controladorJugador=new ControladorJugador();
      controladorCasino=new ControladorCasino();
        //jugador
        
        casino= new Casino();
        //componentes
        jLabelDinero.setVisible(false);
        jLabelNombre.setVisible(false);
        jCrear.setVisible(false);
        jNombre.setVisible(false);
        jDinero.setVisible(false);
        jLabelCasino.setVisible(false);
        jCasino.setVisible(false);
        jAgregar.setVisible(false);
        jCrearCasino.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJugador = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCasino = new javax.swing.JTable();
        jNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jCrear = new javax.swing.JButton();
        jLabelDinero = new javax.swing.JLabel();
        jDinero = new javax.swing.JTextField();
        jBotonCasino = new javax.swing.JButton();
        jCasino = new javax.swing.JTextField();
        jLabelCasino = new javax.swing.JLabel();
        jAgregar = new javax.swing.JButton();
        jCrearCasino = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jButton1.setText("Crear Jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Historial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTableJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nickname", "Dinero", "Ingresos", "Egresos", "Apuestas", "Victorias M1", "Victorias M2", "Victorias M3", "Victorias Totales", "Derrotas M1", "Derrotas M2", "Derrotas M3", "Derrotas Totales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableJugador);

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTableCasino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Dinero", "Ingresos", "Egresos", "Apuestas", "Victorias M1", "Victorias M2", "Victorias M3", "Victorias Totales", "Derrotas M1", "Derrotas M2", "Derrotas M3", "Derrotas Totales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableCasino);

        jLabelNombre.setText("Nombre de Usuario");

        jCrear.setText("Crear");
        jCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearActionPerformed(evt);
            }
        });

        jLabelDinero.setText("Cantidad de Dinero");

        jDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDineroActionPerformed(evt);
            }
        });

        jBotonCasino.setText("Casino");
        jBotonCasino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCasinoActionPerformed(evt);
            }
        });

        jLabelCasino.setText("Cantidad de Dinero");

        jAgregar.setText("Agregar");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jCrearCasino.setText("Crear");
        jCrearCasino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearCasinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jNombre)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jCrear))
                                            .addComponent(jLabelDinero))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCasino)
                                            .addComponent(jBotonCasino)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jCasino, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(jCrearCasino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jAgregar))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jBotonCasino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelDinero)
                    .addComponent(jLabelCasino))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCrear)
                    .addComponent(jDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCasino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAgregar)
                    .addComponent(jCrearCasino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ruletaFrancesa= new RuletaFrancesa();
        ruletaFrancesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
aparecer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDineroActionPerformed

    }//GEN-LAST:event_jDineroActionPerformed

    private void jCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearActionPerformed
     jugador= new Jugador();
     dinero=Double.parseDouble(jDinero.getText());
     jugador.setDerrotasM1(0);
     jugador.setDerrotasM2(0);
     jugador.setDerrotasM3(0);
     jugador.setDinero(dinero);
     jugador.setDineroGanado(0);
     jugador.setDineroPerdido(0);
     jugador.setNickname(jNombre.getText());
     jugador.setVictoriasM1(0);
     jugador.setVictoriasM2(0);
     jugador.setVictoriasM3(0);
     jugador.setdTotales(0);
     jugador.setvTotales(0);
     jugador.setnApuestas(0);
    try {
        controladorJugador.crear(jugador);
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        desaparecer();
    }//GEN-LAST:event_jCrearActionPerformed

    private void jBotonCasinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCasinoActionPerformed
       aparecerCasino();
    }//GEN-LAST:event_jBotonCasinoActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
dCasino=Double.parseDouble(jCasino.getText());
Casino casino1=controladorCasino.buscar(201L);
Double di =casino1.getDinero();
Double suma=dCasino+di;
casino1.setDinero(suma);
    try {
        controladorCasino.actualizar(casino1);
    } catch (Exception ex) {
        Logger.getLogger(VentanaDeOpciones.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jAgregarActionPerformed

    private void jCrearCasinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearCasinoActionPerformed
        dCasino=Double.parseDouble(jCasino.getText());
       casino.setDerrotasM1(0);
       casino.setDerrotasM2(0);
       casino.setDerrotasM3(0);
       casino.setDinero(dCasino);
       casino.setDineroGanado(0);
       casino.setDineroPerdido(0);
       casino.setVictoriasM1(0);
       casino.setVictoriasM2(0);
       casino.setVictoriasM3(0);
       casino.setdTotales(0);
       casino.setvTotales(0);
       casino.setnApuestas(0);
    try {
        controladorCasino.crear(casino);
    } catch (Exception ex) {
        Logger.getLogger(VentanaDeOpciones.class.getName()).log(Level.SEVERE, null, ex);
    }
    desaparecerCasino();
    }//GEN-LAST:event_jCrearCasinoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       cargarDatosCasino();
       cargarDatosJugador();
    }//GEN-LAST:event_jButton2ActionPerformed
public void aparecer(){
jLabelDinero.setVisible(true);
        jLabelNombre.setVisible(true);
        jCrear.setVisible(true);
        jNombre.setVisible(true);
        jDinero.setVisible(true);
}
public void aparecerCasino(){
jLabelCasino.setVisible(true);
        jCasino.setVisible(true);
        jAgregar.setVisible(true);
        jCrearCasino.setVisible(true);
}
public void desaparecerCasino(){
jLabelCasino.setVisible(false);
        jCasino.setVisible(false);
        jAgregar.setVisible(false);
        jCrearCasino.setVisible(false);
        jCasino.setText("");
}
public void desaparecer(){
jLabelDinero.setVisible(false);
        jLabelNombre.setVisible(false);
        jCrear.setVisible(false);
        jNombre.setVisible(false);
        jDinero.setVisible(false);
        jNombre.setText("");
        jDinero.setText("");
}
public void cargarDatosJugador(){
DefaultTableModel modelo = (DefaultTableModel) jTableJugador.getModel();
modelo.setRowCount(0);
controladorJugador.buscarTodo();
    for (Jugador jugador1 : controladorJugador.buscarTodo()) {
        Object[] rowData = {jugador1.getId(),jugador1.getNickname(),jugador1.getDinero(),jugador1.getDineroGanado(),jugador1.getDineroPerdido(),
            jugador1.getnApuestas(),jugador1.getVictoriasM1(),jugador1.getVictoriasM2(),jugador1.getVictoriasM3(),jugador1.getvTotales(),jugador1.getDerrotasM1(),
            jugador1.getDerrotasM2(),jugador1.getDerrotasM3(),jugador1.getdTotales()};
        modelo.addRow(rowData);
    }
    jTableJugador.setModel(modelo);
}
public void cargarDatosCasino(){
DefaultTableModel modelo = (DefaultTableModel) jTableCasino.getModel();
modelo.setRowCount(0);
controladorCasino.buscarTodo();

    for (Casino casino1 : controladorCasino.buscarTodo()) {
      Object[] rowData ={casino1.getId(),casino1.getDinero(),casino1.getDineroGanado(),casino1.getDineroPerdido(),
            casino1.getnApuestas(),casino1.getVictoriasM1(),casino1.getVictoriasM2(),casino1.getVictoriasM3(),casino1.getvTotales(),casino1.getDerrotasM1(),
            casino1.getDerrotasM2(),casino1.getDerrotasM3(),casino1.getdTotales()}; 
      modelo.addRow(rowData); 
    }
    jTableCasino.setModel(modelo);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDeOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregar;
    private javax.swing.JButton jBotonCasino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jCasino;
    private javax.swing.JButton jCrear;
    private javax.swing.JButton jCrearCasino;
    private javax.swing.JTextField jDinero;
    private javax.swing.JLabel jLabelCasino;
    private javax.swing.JLabel jLabelDinero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCasino;
    private javax.swing.JTable jTableJugador;
    // End of variables declaration//GEN-END:variables
}
